apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cycler.serviceAccountName" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cycler.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cycler.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "cycler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}